"""Inicialización de base de datos

Revision ID: 56959f6d98e2
Revises: 
Create Date: 2025-02-08 22:02:17.301959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56959f6d98e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodopago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('usuario', sa.String(length=255), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('legajo'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('egresos',
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('idcategoria', sa.Integer(), nullable=False),
    sa.Column('legajousuario', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('idMetodoPago', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idMetodoPago'], ['metodopago.id'], ),
    sa.ForeignKeyConstraint(['idcategoria'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['legajousuario'], ['usuarios.legajo'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('ingresos',
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('idcategoria', sa.Integer(), nullable=False),
    sa.Column('legajousuario', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['idcategoria'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['legajousuario'], ['usuarios.legajo'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingresos')
    op.drop_table('egresos')
    op.drop_table('usuarios')
    op.drop_table('metodopago')
    op.drop_table('categorias')
    # ### end Alembic commands ###
