"""report

Revision ID: 9ff4fd17312a
Revises: 3364cee460a6
Create Date: 2025-02-10 15:11:06.403304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff4fd17312a'
down_revision = '3364cee460a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legajousuario', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['legajousuario'], ['usuarios.legajo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportes')
    # ### end Alembic commands ###
